### ISSUE TITLE
Plugin doesn't see GraalVM installations

### ISSUE THREAD

**Issue by reinbeumer** [graalvm/vscode-extensions#11] opened 2021-08-21 22:49 UTC
Hi, the plugin won't detect any installed GraalVM.
Not even wen I let the plugin download and install the GraalVM.
Got an error "Failed to add selected Graal VM installation"
On Mac Book Pro OSX BigSur.
java -version:
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Picked up _JAVA_OPTIONS: -Xmx2048m
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)
OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)

**Comment by MartinBalin** [comment] 2021-10-27 06:30
This is very hard to know what was happening in GraalVM Ext. I assume you have GraalVM downloaded already and you was adding it from local disk.

**Comment by fniephaus** [comment] 2021-10-27 06:39
@reinbeumer could you please try again with the latest version of the extension? If the issue is still there, could you please provide steps to reproduce it? Thanks!

**Comment by reinbeumer** [comment] 2021-10-29 15:17
@fniephaus I've tried the last one, dint work.
So I fixed it myself, I wanted to create a pull request for it but I cant figure out how to make one.

**Comment by fniephaus** [comment] 2021-11-03 15:55
Sorry for the inconvenience. How did you fix the issue? BTW: GitHub has some docs on how to submit PRs: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by reinbeumer** [comment] 2021-11-07 23:05
I made a PR, but just like the other PM its rejected by not signing the OCA, witch i did (just like Anthony from the other PR)

**Comment by MartinBalin** [comment] 2022-04-29 07:03
Closing as it works or need more info.

**Closed as completed by MartinBalin** 2022-04-29 07:03 UTC
